version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - depguard
    - dupl
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - gosec
    - lll
    - tagliatelle
    - testpackage
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
