# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.selectel.ru

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

replicaCount: 1
revisionHistoryLimit: 10

image:
  repository: ghcr.io/selectel/cert-manager-webhook-selectel
  tag: v1.4.0
  pullPolicy: Always

imagePullSecrets: []
#  - private-registry

nameOverride: ""
fullnameOverride: ""

extraEnv: []
# - name: SOME_VAR
#   value: "some value"

service:
  type: ClusterIP
  port: 443
  annotations: {}

resources: {}
# limits:
#  cpu: 100m
#  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 65534

containerSecurityContext:
  seLinuxOptions: {}
  runAsUser: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"